import type { MetadataRoute } from "next";

/**
 * Web app manifest. Next serves this at `/manifest.webmanifest` and auto-injects
 * the `<link rel="manifest">`. Icons are generated by `scripts/generate-icons.mjs`.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "LocationLog",
    short_name: "LocationLog",
    description: "Log field locations in seconds.",
    // Start at the login route so a launch always lands somewhere valid; the
    // app routes itself to /log once authenticated.
    start_url: "/",
    scope: "/",
    display: "standalone",
    background_color: "#f3ebe2",
    theme_color: "#c0653c",
    orientation: "portrait",
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icons/maskable-192.png", sizes: "192x192", type: "image/png", purpose: "maskable" },
      { src: "/icons/maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
